module MENU
  BUILD_ANDROID_EMULATOR = 0
  BUILD_IOS_SIMULATOR = 1
  BUILD_FOR_APP_STORE = 2
  BUILD_FOR_GOOGLE_PLAY = 3
  PROMOTE_ANDROID_INTERNAL = 4
  PROMOTE_IOS_TESTFLIGHT = 5
  CODEPUSH_UPDATE = 6
  DOCTOR = 7
  CLEAR_CACHE = 8
end

module ENVIRONMENTS
  STAGING = "staging"
  PRODUCTION = "production"
end

module PLATFORMS
  ANDROID = 0
  IOS = 1
  CODEPUSH = 2
end

module CLEAR_OPTIONS
  ANDROID = 0
  IOS = 1
  ALL = 2
  ALL_EXTREME = 3
end

module VERSION_SELECTIONS
  PATCH = 0
  MINOR = 1
  MAJOR = 2
  KEEP = 3
  CUSTOM = 4
end